[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts@1.1.1/=lib/chainlink-brownie-contracts/contracts",
    "forge-std/=lib/forge-std/src",
    "@solmate=lib/solmate/src",
]
##Giving foundry reading access to broadcast and reports folders:
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 256


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
